(define (less)
    (display (< 5 7))
    (newline)
    (display (< 7 5))
    (newline)
    (display (< 5 5))
    (newline)
)

(define (great)
    (display (> 5 7))
    (newline)
    (display (> 7 5))
    (newline)
    (display (> 5 5))
    (newline)
)

(define (less_equal)
    (display (<= 5 7))
    (newline)
    (display (<= 7 5))
    (newline)
    (display (<= 5 5))
    (newline)
)

(define (great_equal)
    (display (>= 5 7))
    (newline)
    (display (>= 7 5))
    (newline)
    (display (>= 5 5))
    (newline)
)

(define (equal_to num1 num2)
    (display (= num1 num2))
    (newline)
    (display (= (+ num1 1) num2))
    (newline)
    (display (= num1 (+ num2 1)))
    (newline)
)

(define (main)
    (less)  
    (great)
    (less_equal)
    (great_equal)
    (equal_to 6 6)
)
